### ISSUE TITLE
Creating container from 2 threads at once fails

### ISSUE THREAD

**Issue by mynameisguy** [SparkTC/stocator#110]
I have two threads trying to upload object to the same container (which doesn't exists).
once thread creates the container and the second one fails and throw exception:

```
Caused by: Command exception, HTTP Status code: 202 => ENTITY_ALREADY_EXISTS
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:86)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:58)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:542)
	at org.javaswift.joss.exception.HttpStatusToExceptionMapper.getException(HttpStatusToExceptionMapper.java:48)
	at org.javaswift.joss.exception.HttpStatusExceptionUtil.getException(HttpStatusExceptionUtil.java:16)
	at org.javaswift.joss.exception.HttpStatusExceptionUtil.throwException(HttpStatusExceptionUtil.java:10)
	at org.javaswift.joss.command.impl.core.httpstatus.HttpStatusChecker.isOk(HttpStatusChecker.java:30)
	at org.javaswift.joss.command.impl.core.httpstatus.HttpStatusChecker.verifyCode(HttpStatusChecker.java:41)
	at org.javaswift.joss.command.impl.core.AbstractCommand.call(AbstractCommand.java:50)
	at org.javaswift.joss.command.impl.core.AbstractSecureCommand.call(AbstractSecureCommand.java:31)
	at org.javaswift.joss.client.core.AbstractContainer.create(AbstractContainer.java:221)
	at com.ibm.stocator.fs.swift.SwiftAPIClient.initiate(SwiftAPIClient.java:272)
	at com.ibm.stocator.fs.ObjectStoreVisitor.getStoreClient(ObjectStoreVisitor.java:124)
	at com.ibm.stocator.fs.ObjectStoreFileSystem.initialize(ObjectStoreFileSystem.java:90)
```

important point:
**fs.swift2d.impl.disable.cache** is set to **true** which makes init run every time
might be related

**Comment by gilv** [comment]
resolved in https://github.com/SparkTC/stocator/commit/aad1891904f4d444eae09da759689ac342980eb8
