### ISSUE TITLE
Stocator reports 400 unknow error

### ISSUE THREAD

**Issue by kelviolet** [SparkTC/stocator#130]
Command exception, HTTP Status code: 400 => UNKNOWN
	at org.javaswift.joss.command.impl.core.httpstatus.HttpStatusChecker.verifyCode(HttpStatusChecker.java:45)
	at org.javaswift.joss.command.impl.core.AbstractCommand.call(AbstractCommand.java:50)
	at org.javaswift.joss.command.impl.core.AbstractSecureCommand.call(AbstractSecureCommand.java:31)
	at org.javaswift.joss.client.core.AbstractStoredObject.getInfo(AbstractStoredObject.java:267)
	at org.javaswift.joss.client.core.AbstractObjectStoreEntity.checkForInfo(AbstractObjectStoreEntity.java:98)
	at org.javaswift.joss.client.core.AbstractObjectStoreEntity.checkForInfoDisallowErrorLog(AbstractObjectStoreEntity.java:93)
	at org.javaswift.joss.client.core.AbstractObjectStoreEntity.exists(AbstractObjectStoreEntity.java:110)
	at com.ibm.stocator.fs.swift.SwiftAPIClient.getObjectMetadata(SwiftAPIClient.java:316)
	at com.ibm.stocator.fs.swift.SwiftAPIClient.exists(SwiftAPIClient.java:392)
	at com.ibm.stocator.fs.ObjectStoreFileSystem.exists(ObjectStoreFileSystem.java:125)
	at org.apache.hadoop.fs.FileSystem.createNewFile(FileSystem.java:1151)

**Comment by djalova** [comment]
Hi @kelviolet ,
Can I get more information about what you were trying to do?

**Comment by gilv** [comment]
closed due to inactivity
