### ISSUE TITLE
Authentication token expiration in the Swift driver

### ISSUE THREAD

**Issue by gilv** [SparkTC/stocator#15]
I never tested what happens if authentication token expires.
For example, Spark saves 1000 tasks, each task persist it's relevant data - part-XXXX.

What happens if token expired in the middle?
The same for read operations.

Some functions in the code doesn't contain "Retry authentication", for example createObject in SwiftAPIClient. There should be coverage for retry in case of authentication token expire.

Also, need to test how JOSS behaves, when token expire ( JOSS suppose to cover it )

**Comment by charles2588** [comment]
Hi gliv,

I just tested the token failure with Bluemix Object Storage Service.
I hope it helps.
Bluemix Object Storage Service's Keystone V3 response mentions:-
"issued_at": "2016-03-10T19:26:41.000000Z"
"expires_at": "2016-03-10T20:26:41.337443Z"
So i believe the token for Bluemix object storage service stays valid for about 1 hour

Test:-
Loaded spark-shell with stocator jar.
SQL context available as sqlContext.

scala> val data = Array(1, 2, 3, 4, 5, 6, 7, 8)
data: Array[Int] = Array(1, 2, 3, 4, 5, 6, 7, 8)

scala> val distData = sc.parallelize(data)
distData: org.apache.spark.rdd.RDD[Int] = ParallelCollectionRDD[0] at parallelize at <console>:29

scala> import java.util.Calendar
import java.util.Calendar

scala> Calendar.getInstance().getTime()
res3: java.util.Date = Thu Mar 10 14:38:26 EST 2016
**
1st attempt to save the file:success**
scala> distData.saveAsTextFile("swift2d://newcontainer.dal05/first.txt")
16/03/10 14:38:34 INFO impl.ClientImpl: JOSS / Creating real account instance
**16/03/10 14:38:34 INFO impl.ClientImpl: JOSS / * Allow caching: true**
16/03/10 14:38:34 INFO impl.ClientImpl: JOSS / Attempting authentication with tenant name: null, tenant ID: null, username: null, Auth URL: https://identity.open.softlayer.com/v3/auth/tokens
16/03/10 14:38:40 INFO impl.ClientImpl: JOSS / Successfully authenticated
16/03/10 14:38:40 INFO impl.ClientImpl: JOSS / Applying preferred region: dallas
16/03/10 14:38:40 INFO impl.ClientImpl: JOSS / Using TempURL hash prefix source: PUBLIC_URL_PATH
16/03/10 14:38:42 INFO core.ServerTime: JOSS / Server time is Thu, 10 Mar 2016 19:38:42 GMT
16/03/10 14:38:42 INFO core.ServerTime: JOSS / Local time is Thu, 10 Mar 2016 19:38:42 GMT
16/03/10 14:38:42 INFO core.ServerTime: JOSS / Local time modifier in milliseconds: -728
16/03/10 14:38:42 INFO core.AbstractAccount: JOSS / Use public host: null
16/03/10 14:38:42 INFO core.AbstractAccount: JOSS / Use private host: null
16/03/10 14:38:42 INFO core.AbstractAccount: JOSS / Allow Container caching: true
16/03/10 14:38:42 INFO core.AbstractAccount: JOSS / Allow reauthentication: true
16/03/10 14:38:42 INFO core.AbstractAccount: JOSS / Setting hash password
16/03/10 14:38:44 INFO Configuration.deprecation: mapred.tip.id is deprecated. Instead, use mapreduce.task.id
16/03/10 14:38:44 INFO Configuration.deprecation: mapred.task.id is deprecated. Instead, use mapreduce.task.attempt.id
16/03/10 14:38:44 INFO Configuration.deprecation: mapred.task.is.map is deprecated. Instead, use mapreduce.task.ismap
16/03/10 14:38:44 INFO Configuration.deprecation: mapred.task.partition is deprecated. Instead, use mapreduce.task.partition
16/03/10 14:38:44 INFO Configuration.deprecation: mapred.job.id is deprecated. Instead, use mapreduce.job.id
16/03/10 14:38:45 INFO spark.SparkContext: Starting job: saveAsTextFile at <console>:33
16/03/10 14:38:45 INFO scheduler.DAGScheduler: Got job 0 (saveAsTextFile at <console>:33) with 1 output partitions
16/03/10 14:38:45 INFO scheduler.DAGScheduler: Final stage: ResultStage 0 (saveAsTextFile at <console>:33)
16/03/10 14:38:45 INFO scheduler.DAGScheduler: Parents of final stage: List()
16/03/10 14:38:45 INFO scheduler.DAGScheduler: Missing parents: List()
16/03/10 14:38:45 INFO scheduler.DAGScheduler: Submitting ResultStage 0 (MapPartitionsRDD[2] at saveAsTextFile at <console>:33), which has no missing parents
16/03/10 14:38:46 INFO storage.MemoryStore: Block broadcast_0 stored as values in memory (estimated size 64.2 KB, free 64.2 KB)
16/03/10 14:38:47 INFO storage.MemoryStore: Block broadcast_0_piece0 stored as bytes in memory (estimated size 22.0 KB, free 86.2 KB)
16/03/10 14:38:47 INFO storage.BlockManagerInfo: Added broadcast_0_piece0 in memory on localhost:38367 (size: 22.0 KB, free: 543.0 MB)
16/03/10 14:38:47 INFO spark.SparkContext: Created broadcast 0 from broadcast at DAGScheduler.scala:1006
16/03/10 14:38:47 INFO scheduler.DAGScheduler: Submitting 1 missing tasks from ResultStage 0 (MapPartitionsRDD[2] at saveAsTextFile at <console>:33)
16/03/10 14:38:47 INFO scheduler.TaskSchedulerImpl: Adding task set 0.0 with 1 tasks
16/03/10 14:38:47 INFO scheduler.TaskSetManager: Starting task 0.0 in stage 0.0 (TID 0, localhost, partition 0,PROCESS_LOCAL, 2131 bytes)
16/03/10 14:38:47 INFO executor.Executor: Running task 0.0 in stage 0.0 (TID 0)
16/03/10 14:38:47 INFO executor.Executor: Fetching http://9.24.186.152:39923/jars/stocator-1.0.0-jar-with-dependencies.jar with timestamp 1457637435526
16/03/10 14:38:48 INFO util.Utils: Fetching http://9.24.186.152:39923/jars/stocator-1.0.0-jar-with-dependencies.jar to /tmp/spark-45120ed5-c15c-41c8-a8a6-da45c49b7b53/userFiles-2aa2dcd9-7c65-47f9-8648-9871d5c5e55e/fetchFileTemp4928856443441187361.tmp
16/03/10 14:38:51 INFO executor.Executor: Adding file:/tmp/spark-45120ed5-c15c-41c8-a8a6-da45c49b7b53/userFiles-2aa2dcd9-7c65-47f9-8648-9871d5c5e55e/stocator-1.0.0-jar-with-dependencies.jar to class loader
16/03/10 14:38:53 INFO mapred.SparkHadoopMapRedUtil: No need to commit output of task because needsTaskCommit=false: attempt_201603101438_0000_m_000000_0
16/03/10 14:38:53 INFO executor.Executor: Finished task 0.0 in stage 0.0 (TID 0). 1864 bytes result sent to driver
16/03/10 14:38:53 INFO scheduler.DAGScheduler: ResultStage 0 (saveAsTextFile at <console>:33) finished in 6.651 s
16/03/10 14:38:53 INFO scheduler.TaskSetManager: Finished task 0.0 in stage 0.0 (TID 0) in 6197 ms on localhost (1/1)
16/03/10 14:38:53 INFO scheduler.TaskSchedulerImpl: Removed TaskSet 0.0, whose tasks have all completed, from pool 
16/03/10 14:38:54 INFO scheduler.DAGScheduler: Job 0 finished: saveAsTextFile at <console>:33, took 8.621661 s

**2nd attempt to save the file :- success**
scala> distData.saveAsTextFile("swift2d://newcontainer.dal05/two.txt")
16/03/10 14:39:15 INFO spark.SparkContext: Starting job: saveAsTextFile at <console>:33
16/03/10 14:39:15 INFO scheduler.DAGScheduler: Got job 1 (saveAsTextFile at <console>:33) with 1 output partitions
16/03/10 14:39:15 INFO scheduler.DAGScheduler: Final stage: ResultStage 1 (saveAsTextFile at <console>:33)
16/03/10 14:39:15 INFO scheduler.DAGScheduler: Parents of final stage: List()
16/03/10 14:39:15 INFO scheduler.DAGScheduler: Missing parents: List()
16/03/10 14:39:15 INFO scheduler.DAGScheduler: Submitting ResultStage 1 (MapPartitionsRDD[3] at saveAsTextFile at <console>:33), which has no missing parents
16/03/10 14:39:16 INFO storage.MemoryStore: Block broadcast_1 stored as values in memory (estimated size 64.2 KB, free 150.5 KB)
16/03/10 14:39:16 INFO storage.MemoryStore: Block broadcast_1_piece0 stored as bytes in memory (estimated size 22.0 KB, free 172.4 KB)
16/03/10 14:39:16 INFO storage.BlockManagerInfo: Added broadcast_1_piece0 in memory on localhost:38367 (size: 22.0 KB, free: 543.0 MB)
16/03/10 14:39:16 INFO spark.SparkContext: Created broadcast 1 from broadcast at DAGScheduler.scala:1006
16/03/10 14:39:16 INFO scheduler.DAGScheduler: Submitting 1 missing tasks from ResultStage 1 (MapPartitionsRDD[3] at saveAsTextFile at <console>:33)
16/03/10 14:39:16 INFO scheduler.TaskSchedulerImpl: Adding task set 1.0 with 1 tasks
16/03/10 14:39:16 INFO scheduler.TaskSetManager: Starting task 0.0 in stage 1.0 (TID 1, localhost, partition 0,PROCESS_LOCAL, 2131 bytes)
16/03/10 14:39:16 INFO executor.Executor: Running task 0.0 in stage 1.0 (TID 1)
16/03/10 14:39:17 INFO mapred.SparkHadoopMapRedUtil: No need to commit output of task because needsTaskCommit=false: attempt_201603101439_0001_m_000000_1
16/03/10 14:39:17 INFO executor.Executor: Finished task 0.0 in stage 1.0 (TID 1). 1864 bytes result sent to driver
16/03/10 14:39:17 INFO scheduler.DAGScheduler: ResultStage 1 (saveAsTextFile at <console>:33) finished in 1.094 s
16/03/10 14:39:17 INFO scheduler.DAGScheduler: Job 1 finished: saveAsTextFile at <console>:33, took 1.266169 s
16/03/10 14:39:17 INFO scheduler.TaskSetManager: Finished task 0.0 in stage 1.0 (TID 1) in 1093 ms on localhost (1/1)
16/03/10 14:39:17 INFO scheduler.TaskSchedulerImpl: Removed TaskSet 1.0, whose tasks have all completed, from pool 

scala> import java.lang.Thread
import java.lang.Thread                                               ^

Make the thread sleep for 1 hour
scala> Thread.sleep(1000 * 60 * 60)
16/03/10 14:47:17 INFO spark.ContextCleaner: Cleaned accumulator 1
16/03/10 14:47:18 INFO storage.BlockManagerInfo: Removed broadcast_0_piece0 on localhost:38367 in memory (size: 22.0 KB, free: 543.0 MB)
16/03/10 14:47:18 INFO spark.ContextCleaner: Cleaned accumulator 2
16/03/10 14:47:18 INFO storage.BlockManagerInfo: Removed broadcast_1_piece0 on localhost:38367 in memory (size: 22.0 KB, free: 543.0 MB)
**
Attempt 3 to save file:Failure**
scala> distData.saveAsTextFile("swift2d://newcontainer.dal05/three.txt")
16/03/10 16:41:20 INFO spark.SparkContext: Starting job: saveAsTextFile at <console>:34
16/03/10 16:41:20 INFO scheduler.DAGScheduler: Got job 2 (saveAsTextFile at <console>:34) with 1 output partitions
16/03/10 16:41:20 INFO scheduler.DAGScheduler: Final stage: ResultStage 2 (saveAsTextFile at <console>:34)
16/03/10 16:41:20 INFO scheduler.DAGScheduler: Parents of final stage: List()
16/03/10 16:41:20 INFO scheduler.DAGScheduler: Missing parents: List()
16/03/10 16:41:20 INFO scheduler.DAGScheduler: Submitting ResultStage 2 (MapPartitionsRDD[4] at saveAsTextFile at <console>:34), which has no missing parents
16/03/10 16:41:21 INFO storage.MemoryStore: Block broadcast_2 stored as values in memory (estimated size 64.2 KB, free 64.2 KB)
16/03/10 16:41:21 INFO storage.MemoryStore: Block broadcast_2_piece0 stored as bytes in memory (estimated size 22.0 KB, free 86.2 KB)
16/03/10 16:41:21 INFO storage.BlockManagerInfo: Added broadcast_2_piece0 in memory on localhost:38367 (size: 22.0 KB, free: 543.0 MB)
16/03/10 16:41:21 INFO spark.SparkContext: Created broadcast 2 from broadcast at DAGScheduler.scala:1006
16/03/10 16:41:21 INFO scheduler.DAGScheduler: Submitting 1 missing tasks from ResultStage 2 (MapPartitionsRDD[4] at saveAsTextFile at <console>:34)
16/03/10 16:41:21 INFO scheduler.TaskSchedulerImpl: Adding task set 2.0 with 1 tasks
16/03/10 16:41:21 INFO scheduler.TaskSetManager: Starting task 0.0 in stage 2.0 (TID 2, localhost, partition 0,PROCESS_LOCAL, 2131 bytes)
16/03/10 16:41:21 INFO executor.Executor: Running task 0.0 in stage 2.0 (TID 2)
16/03/10 16:41:22 ERROR swift.SwiftOutputStream: 
16/03/10 16:41:22 ERROR executor.Executor: Exception in task 0.0 in stage 2.0 (TID 2)
j**ava.lang.NullPointerException
	at com.ibm.stocator.fs.swift.SwiftOutputStream.close(SwiftOutputStream.java:99)**
	at org.apache.hadoop.fs.FSDataOutputStream$PositionCache.close(FSDataOutputStream.java:72)
	at org.apache.hadoop.fs.FSDataOutputStream.close(FSDataOutputStream.java:106)
	at org.apache.hadoop.mapred.TextOutputFormat$LineRecordWriter.close(TextOutputFormat.java:108)
	at org.apache.spark.SparkHadoopWriter.close(SparkHadoopWriter.scala:103)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1$$anonfun$13$$anonfun$apply$7.apply$mcV$sp(PairRDDFunctions.scala:1206)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1259)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1$$anonfun$13.apply(PairRDDFunctions.scala:1205)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1$$anonfun$13.apply(PairRDDFunctions.scala:1185)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:89)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:213)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1157)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:627)
	at java.lang.Thread.run(Thread.java:798)
16/03/10 16:41:22 WARN scheduler.TaskSetManager: Lost task 0.0 in stage 2.0 (TID 2, localhost): java.lang.NullPointerException
	at com.ibm.stocator.fs.swift.SwiftOutputStream.close(SwiftOutputStream.java:99)
	at org.apache.hadoop.fs.FSDataOutputStream$PositionCache.close(FSDataOutputStream.java:72)
	at org.apache.hadoop.fs.FSDataOutputStream.close(FSDataOutputStream.java:106)
	at org.apache.hadoop.mapred.TextOutputFormat$LineRecordWriter.close(TextOutputFormat.java:108)
	at org.apache.spark.SparkHadoopWriter.close(SparkHadoopWriter.scala:103)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1$$anonfun$13$$anonfun$apply$7.apply$mcV$sp(PairRDDFunctions.scala:1206)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1259)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1$$anonfun$13.apply(PairRDDFunctions.scala:1205)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1$$anonfun$13.apply(PairRDDFunctions.scala:1185)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:89)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:213)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1157)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:627)
	at java.lang.Thread.run(Thread.java:798)

16/03/10 16:41:22 ERROR scheduler.TaskSetManager: Task 0 in stage 2.0 failed 1 times; aborting job
16/03/10 16:41:22 INFO scheduler.TaskSchedulerImpl: Removed TaskSet 2.0, whose tasks have all completed, from pool 
16/03/10 16:41:22 INFO scheduler.TaskSchedulerImpl: Cancelling stage 2
16/03/10 16:41:22 INFO scheduler.DAGScheduler: ResultStage 2 (saveAsTextFile at <console>:34) failed in 1.668 s
16/03/10 16:41:22 INFO scheduler.DAGScheduler: Job 2 failed: saveAsTextFile at <console>:34, took 2.068731 s
org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 2.0 failed 1 times, most recent failure: Lost task 0.0 in stage 2.0 (TID 2, localhost): java.lang.NullPointerException
	at com.ibm.stocator.fs.swift.SwiftOutputStream.close(SwiftOutputStream.java:99)
	at org.apache.hadoop.fs.FSDataOutputStream$PositionCache.close(FSDataOutputStream.java:72)
	at org.apache.hadoop.fs.FSDataOutputStream.close(FSDataOutputStream.java:106)
	at org.apache.hadoop.mapred.TextOutputFormat$LineRecordWriter.close(TextOutputFormat.java:108)
	at org.apache.spark.SparkHadoopWriter.close(SparkHadoopWriter.scala:103)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1$$anonfun$13$$anonfun$apply$7.apply$mcV$sp(PairRDDFunctions.scala:1206)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1259)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1$$anonfun$13.apply(PairRDDFunctions.scala:1205)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1$$anonfun$13.apply(PairRDDFunctions.scala:1185)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:89)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:213)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1157)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:627)
	at java.lang.Thread.run(Thread.java:798)

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1431)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1419)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1418)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1418)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:799)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:799)
	at scala.Option.foreach(Option.scala:236)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:799)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1640)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1599)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1588)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
	at java.lang.Thread.getStackTrace(Thread.java:1133)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:620)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1832)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1845)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1922)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1.apply$mcV$sp(PairRDDFunctions.scala:1213)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1.apply(PairRDDFunctions.scala:1156)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1.apply(PairRDDFunctions.scala:1156)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:150)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:111)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:316)
	at org.apache.spark.rdd.PairRDDFunctions.saveAsHadoopDataset(PairRDDFunctions.scala:1156)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopFile$4.apply$mcV$sp(PairRDDFunctions.scala:1060)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopFile$4.apply(PairRDDFunctions.scala:1026)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopFile$4.apply(PairRDDFunctions.scala:1026)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:150)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:111)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:316)
	at org.apache.spark.rdd.PairRDDFunctions.saveAsHadoopFile(PairRDDFunctions.scala:1026)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopFile$1.apply$mcV$sp(PairRDDFunctions.scala:952)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopFile$1.apply(PairRDDFunctions.scala:952)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopFile$1.apply(PairRDDFunctions.scala:952)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:150)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:111)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:316)
	at org.apache.spark.rdd.PairRDDFunctions.saveAsHadoopFile(PairRDDFunctions.scala:951)
	at org.apache.spark.rdd.RDD$$anonfun$saveAsTextFile$1.apply$mcV$sp(RDD.scala:1443)
	at org.apache.spark.rdd.RDD$$anonfun$saveAsTextFile$1.apply(RDD.scala:1422)
	at org.apache.spark.rdd.RDD$$anonfun$saveAsTextFile$1.apply(RDD.scala:1422)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:150)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:111)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:316)
	at org.apache.spark.rdd.RDD.saveAsTextFile(RDD.scala:1422)
	at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:34)
	at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:39)
	at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:41)
	at $iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:43)
	at $iwC$$iwC$$iwC$$iwC.<init>(<console>:45)
	at $iwC$$iwC$$iwC.<init>(<console>:47)
	at $iwC$$iwC.<init>(<console>:49)
	at $iwC.<init>(<console>:51)
	at <init>(<console>:53)
	at .<init>(<console>:57)
	at .<clinit>(<console>)
	at java.lang.J9VMInternals.initializeImpl(Native Method)
	at java.lang.J9VMInternals.initialize(J9VMInternals.java:235)
	at .<init>(<console>:7)
	at .<clinit>(<console>)
	at java.lang.J9VMInternals.initializeImpl(Native Method)
	at java.lang.J9VMInternals.initialize(J9VMInternals.java:235)
	at $print(<console>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:95)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:56)
	at java.lang.reflect.Method.invoke(Method.java:620)
	at org.apache.spark.repl.SparkIMain$ReadEvalPrint.call(SparkIMain.scala:1065)
	at org.apache.spark.repl.SparkIMain$Request.loadAndRun(SparkIMain.scala:1346)
	at org.apache.spark.repl.SparkIMain.loadAndRunReq$1(SparkIMain.scala:840)
	at org.apache.spark.repl.SparkIMain.interpret(SparkIMain.scala:871)
	at org.apache.spark.repl.SparkIMain.interpret(SparkIMain.scala:819)
	at org.apache.spark.repl.SparkILoop.reallyInterpret$1(SparkILoop.scala:857)
	at org.apache.spark.repl.SparkILoop.interpretStartingWith(SparkILoop.scala:902)
	at org.apache.spark.repl.SparkILoop.command(SparkILoop.scala:814)
	at org.apache.spark.repl.SparkILoop.processLine$1(SparkILoop.scala:657)
	at org.apache.spark.repl.SparkILoop.innerLoop$1(SparkILoop.scala:665)
	at org.apache.spark.repl.SparkILoop.org$apache$spark$repl$SparkILoop$$loop(SparkILoop.scala:670)
	at org.apache.spark.repl.SparkILoop$$anonfun$org$apache$spark$repl$SparkILoop$$process$1.apply$mcZ$sp(SparkILoop.scala:997)
	at org.apache.spark.repl.SparkILoop$$anonfun$org$apache$spark$repl$SparkILoop$$process$1.apply(SparkILoop.scala:945)
	at org.apache.spark.repl.SparkILoop$$anonfun$org$apache$spark$repl$SparkILoop$$process$1.apply(SparkILoop.scala:945)
	at scala.tools.nsc.util.ScalaClassLoader$.savingContextLoader(ScalaClassLoader.scala:135)
	at org.apache.spark.repl.SparkILoop.org$apache$spark$repl$SparkILoop$$process(SparkILoop.scala:945)
	at org.apache.spark.repl.SparkILoop.process(SparkILoop.scala:1059)
	at org.apache.spark.repl.Main$.main(Main.scala:31)
	at org.apache.spark.repl.Main.main(Main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:95)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:56)
	at java.lang.reflect.Method.invoke(Method.java:620)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:731)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.NullPointerException
	at com.ibm.stocator.fs.swift.SwiftOutputStream.close(SwiftOutputStream.java:99)
	at org.apache.hadoop.fs.FSDataOutputStream$PositionCache.close(FSDataOutputStream.java:72)
	at org.apache.hadoop.fs.FSDataOutputStream.close(FSDataOutputStream.java:106)
	at org.apache.hadoop.mapred.TextOutputFormat$LineRecordWriter.close(TextOutputFormat.java:108)
	at org.apache.spark.SparkHadoopWriter.close(SparkHadoopWriter.scala:103)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1$$anonfun$13$$anonfun$apply$7.apply$mcV$sp(PairRDDFunctions.scala:1206)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1259)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1$$anonfun$13.apply(PairRDDFunctions.scala:1205)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1$$anonfun$13.apply(PairRDDFunctions.scala:1185)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:89)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:213)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1157)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:627)
	at java.lang.Thread.run(Thread.java:798)

Thanks,
Charles.

**Comment by rjd60** [comment]
Hi Gil,

This is a real issue for us: we have an application that runs indefinitely, and after an hour so (using Bluemix Object Storage) updates start to fail. It seems that reads are still OK which implies that JOSS is doing the right thing. Why does it not use JOSS for updates also?

Thanks,
Rob

**Comment by gilv** [comment]
@rjd60 Done. About to make new release
