### ISSUE TITLE
Question: swift url for solftlayer?

### ISSUE THREAD

**Issue by snowch** [SparkTC/stocator#43]
When saving a file to softlayer, the example on the README is this:

```
sc.textFile("swift2d://dal05.objectstorage.softlayer.net/v1/AUTH_ID/CONT/data.csv")
```

Where do I get the AUTH_ID from?

**Comment by gilv** [comment]
@snowch This is example related public containers only.
Otherwise, auth url is of the form: https://dal05.objectstorage.softlayer.net/auth/v1.0 ( for example Dallas )

**Comment by snowch** [comment]
Hi @gilv - sorry not following.  Should I be using this?

```
    # destination url
    if (os_auth_method == 'swiftauth'):
        # E.g. SoftLayer
        url = os_auth_url.replace('https://', '')
        url = re.sub('\/$', '', url) # remove trailing forward slash if exists

        swift_file_url = "swift2d://{0}/counts".format(url)
    else:
        swift_file_url = "swift2d://{0}.{1}/counts".format(os_container, os_region)

   counts.saveAsTextFile(swift_file_url)
```
The swift file url is: `swift2d://lon02.objectstorage.softlayer.net/auth/v1.0/counts`

```
bicluster#7|Traceback (most recent call last):
bicluster#7|  File "/home/biadmin/test-1463037210878/exporttoswift.py", line 81, in <module>
bicluster#7|    counts.saveAsTextFile(swift_file_url)
bicluster#7|  File "/usr/iop/4.1.0.0/spark/python/lib/pyspark.zip/pyspark/rdd.py", line 1508, in saveAsTextFile
bicluster#7|  File "/usr/iop/4.1.0.0/spark/python/lib/py4j-0.8.2.1-src.zip/py4j/java_gateway.py", line 538, in __call__
bicluster#7|  File "/usr/iop/4.1.0.0/spark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 36, in deco
bicluster#7|  File "/usr/iop/4.1.0.0/spark/python/lib/py4j-0.8.2.1-src.zip/py4j/protocol.py", line 300, in get_return_value
bicluster#7|py4j.protocol.Py4JJavaError: An error occurred while calling o86.saveAsTextFile.
bicluster#7|: Command exception, HTTP Status code: 400 => UNKNOWN
```

The counts container exists in softlayer.

**Comment by snowch** [comment]
@djalova - are you able to point me in the right direction with this?

**Comment by gilv** [comment]
@snowch I am not sure i understand. You connect to SL the same way you connect to Bluemix object service or any other Swift cluster. Just provide auth url to SL and that's it.

**Comment by snowch** [comment]
Thanks @gilv @djalova - sorted now.
