### ISSUE TITLE
Running the same SQL couple of time may throw java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by gilv** [SparkTC/stocator#44]
I used some SQL on Parquet file.
First run was ok. I then re-run the query again and got

16/05/26 08:45:04 DEBUG SwiftInputStream: negative seek
16/05/26 08:45:04 DEBUG SwiftInputStream: Reading 6619446 bytes starting at 6553910
16/05/26 08:45:04 WARN TaskSetManager: Lost task 5.0 in stage 9.0 (TID 472, localhost): java.lang.IndexOutOfBoundsException
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:90)
	at org.apache.http.impl.io.AbstractSessionInputBuffer.fillBuffer(AbstractSessionInputBuffer.java:160)
	at org.apache.http.impl.io.SocketInputBuffer.fillBuffer(SocketInputBuffer.java:84)
	at org.apache.http.impl.io.SocketInputBuffer.isDataAvailable(SocketInputBuffer.java:95)
	at org.apache.http.impl.AbstractHttpClientConnection.isStale(AbstractHttpClientConnection.java:310)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.isStale(ManagedClientConnectionImpl.java:163)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:434)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:884)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at org.javaswift.joss.command.impl.core.AbstractCommand.call(AbstractCommand.java:49)
	at org.javaswift.joss.command.impl.factory.AccountCommandFactoryImpl.authenticate(AccountCommandFactoryImpl.java:66)
	at org.javaswift.joss.client.core.AbstractAccount.authenticate(AbstractAccount.java:171)
	at com.ibm.stocator.fs.swift.SwiftInputStream.loadIntoBuffer(SwiftInputStream.java:259)
	at com.ibm.stocator.fs.swift.SwiftInputStream.seek(SwiftInputStream.java:246)
	at org.apache.hadoop.fs.FSDataInputStream.seek(FSDataInputStream.java:62)
	at org.apache.parquet.hadoop.ParquetFileReader.readFooter(ParquetFileReader.java:429)
	at org.apache.parquet.hadoop.ParquetFileReader.readFooter(ParquetFileReader.java:385)
	at org.apache.spark.sql.execution.datasources.parquet.SpecificParquetRecordReaderBase.initialize(SpecificParquetRecordReaderBase.java:100)
	at org.apache.spark.sql.execution.datasources.parquet.VectorizedParquetRecordReader.initialize(VectorizedParquetRecordReader.java:109)
	at org.apache.spark.sql.execution.datasources.parquet.DefaultSource$$anonfun$buildReader$1.apply(ParquetRelation.scala:349)
	at org.apache.spark.sql.execution.datasources.parquet.DefaultSource$$anonfun$buildReader$1.apply(ParquetRelation.scala:328)
	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.nextIterator(FileScanRDD.scala:114)
	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.hasNext(FileScanRDD.scala:91)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.scan_nextBatch$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$7$$anon$1.hasNext(WholeStageCodegenExec.scala:359)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.agg_doAggregateWithKeys$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$7$$anon$1.hasNext(WholeStageCodegenExec.scala:359)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:125)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:79)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:47)
	at org.apache.spark.scheduler.Task.run(Task.scala:85)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by djalova** [comment]
Seems to be caused by using a deprecated version of HttpClient.
Relevant PR: #46
